"""Added score model

Revision ID: 21318f9fbe9d
Revises: ac6061d1ed5a
Create Date: 2023-05-28 19:41:59.283407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21318f9fbe9d'
down_revision = 'ac6061d1ed5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=200), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(collation='utf8mb4_polish_ci', length=200), nullable=False))
        batch_op.drop_column('level')

    # ### end Alembic commands ###
