"""Quiz Model added

Revision ID: 5132ad120da3
Revises: 6456b42bce0e
Create Date: 2023-05-23 10:13:41.473012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5132ad120da3'
down_revision = '6456b42bce0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('option3',
               existing_type=mysql.VARCHAR(collation='utf8mb4_polish_ci', length=255),
               nullable=True)
        batch_op.alter_column('option4',
               existing_type=mysql.VARCHAR(collation='utf8mb4_polish_ci', length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('option4',
               existing_type=mysql.VARCHAR(collation='utf8mb4_polish_ci', length=255),
               nullable=False)
        batch_op.alter_column('option3',
               existing_type=mysql.VARCHAR(collation='utf8mb4_polish_ci', length=255),
               nullable=False)

    # ### end Alembic commands ###
