"""Changed characters type

Revision ID: ac6061d1ed5a
Revises: b48943875832
Create Date: 2023-05-28 16:12:45.284010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac6061d1ed5a'
down_revision = 'b48943875832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('characters',
               existing_type=mysql.TEXT(collation='utf8mb4_polish_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('characters',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_polish_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
