"""Words model added

Revision ID: b48943875832
Revises: ce7bdc2abd36
Create Date: 2023-05-28 13:51:58.802669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b48943875832'
down_revision = 'ce7bdc2abd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters', sa.Text(), nullable=True))
        batch_op.alter_column('video',
               existing_type=mysql.VARCHAR(collation='utf8mb4_polish_ci', length=120),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_polish_ci', length=120),
               existing_nullable=True)
        batch_op.drop_column('characters')

    # ### end Alembic commands ###
