"""Added quiz_score field

Revision ID: ce7bdc2abd36
Revises: 5132ad120da3
Create Date: 2023-05-25 21:36:08.990911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7bdc2abd36'
down_revision = '5132ad120da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('quiz_score')

    # ### end Alembic commands ###
