"""Changed level to type

Revision ID: f60a925c797c
Revises: 21318f9fbe9d
Create Date: 2023-05-28 19:43:43.060396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f60a925c797c'
down_revision = '21318f9fbe9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=200), nullable=False))
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(collation='utf8mb4_polish_ci', length=200), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
